server:
  port: 8085
  servlet:
    context-path: '/ead-notification/'

spring:
  application:
    name: ead-notification

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
