server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'

spring:
  application:
    name: ead-authuser-service-v2
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/ead-authuser
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    com.ead: TRACE
    org.springframework.web: DEBUG

ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

