server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service-v2
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/ead-course
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    com.ead: TRACE
    org.springframework.web: DEBUG

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'

eureka:
  client:
    serviceUrl:
      defaltZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost