server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/ead-course
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    com.ead: TRACE
    org.springframework.web: DEBUG