version: '3'

services:
  postgress-database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  ead-platfom-pgadmin:
    image: dpage/pgadmin4:4.23
    ports:
      - 5433:80
    env_file:
      - .env
    depends_on:
      - postgress-database
    networks:
      - postgres-network
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/

networks:
  postgres-network:
    driver: bridge